package br.com.sobrevida.vacinaSARSCoV2.view;

import br.com.sobrevida.vacinaSARSCoV2.controller.RelatorioController;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WERIKE
 */
public class GerarRelatorio extends javax.swing.JFrame {

    public GerarRelatorio() {
        initComponents();
        
        //ALTERANDO O ICONE PADRAO DO JAVA
        IconeSistema iconeSistema = new IconeSistema();
        iconeSistema.inserirIcone(this);
        
        avisoDe.setVisible(false);
        avisoPara.setVisible(false);
        
        imprimirCarregar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avisoSenha = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        linhaSeparador1 = new javax.swing.JSeparator();
        jLabel69 = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        para = new javax.swing.JFormattedTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        avisoPara = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        de = new javax.swing.JFormattedTextField();
        avisoDe = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        imprimirCarregar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobrevida - Controle de Aplicações");
        setMinimumSize(new java.awt.Dimension(763, 352));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        avisoSenha.setBackground(new java.awt.Color(255, 255, 255));
        avisoSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        avisoSenha.setMaximumSize(new java.awt.Dimension(840, 400));
        avisoSenha.setPreferredSize(new java.awt.Dimension(840, 400));
        avisoSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avisoSenhaMouseClicked(evt);
            }
        });
        avisoSenha.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 44, 52));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Controle de aplicações");
        avisoSenha.add(jLabel1);
        jLabel1.setBounds(60, 20, 250, 23);
        avisoSenha.add(linhaSeparador1);
        linhaSeparador1.setBounds(20, 50, 720, 2);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/controleAplicacao.png"))); // NOI18N
        avisoSenha.add(jLabel69);
        jLabel69.setBounds(22, 18, 30, 30);

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/impri4.png"))); // NOI18N
        imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimirMouseClicked(evt);
            }
        });
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });
        avisoSenha.add(imprimir);
        imprimir.setBounds(670, 70, 40, 40);

        para.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        try {
            para.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        para.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        avisoSenha.add(para);
        para.setBounds(480, 80, 100, 28);

        jLabel71.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(102, 102, 102));
        jLabel71.setText("Gerar relatório");
        avisoSenha.add(jLabel71);
        jLabel71.setBounds(650, 120, 100, 15);

        jLabel61.setBackground(new java.awt.Color(51, 51, 51));
        jLabel61.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(51, 51, 51));
        jLabel61.setText("Qual a data da aplicação?");
        avisoSenha.add(jLabel61);
        jLabel61.setBounds(20, 90, 170, 16);

        avisoPara.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avisoPara.setForeground(new java.awt.Color(255, 0, 0));
        avisoPara.setText("*");
        avisoSenha.add(avisoPara);
        avisoPara.setBounds(470, 80, 10, 15);

        jLabel62.setBackground(new java.awt.Color(51, 51, 51));
        jLabel62.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(51, 51, 51));
        jLabel62.setText("Para");
        avisoSenha.add(jLabel62);
        jLabel62.setBounds(438, 90, 30, 16);

        jLabel63.setBackground(new java.awt.Color(51, 51, 51));
        jLabel63.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(51, 51, 51));
        jLabel63.setText("De");
        avisoSenha.add(jLabel63);
        jLabel63.setBounds(250, 90, 30, 16);

        de.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        try {
            de.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        de.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        avisoSenha.add(de);
        de.setBounds(280, 80, 100, 28);

        avisoDe.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        avisoDe.setForeground(new java.awt.Color(255, 0, 0));
        avisoDe.setText("*");
        avisoSenha.add(avisoDe);
        avisoDe.setBounds(270, 80, 10, 15);

        jLabel73.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(102, 102, 102));
        jLabel73.setText("Inicio");
        avisoSenha.add(jLabel73);
        jLabel73.setBounds(280, 110, 70, 15);

        jLabel72.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(102, 102, 102));
        jLabel72.setText("Fim");
        avisoSenha.add(jLabel72);
        jLabel72.setBounds(480, 110, 70, 15);

        imprimirCarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imprimir40.gif"))); // NOI18N
        avisoSenha.add(imprimirCarregar);
        imprimirCarregar.setBounds(700, 5, 40, 40);

        getContentPane().add(avisoSenha);
        avisoSenha.setBounds(0, 0, 770, 360);

        getAccessibleContext().setAccessibleDescription("Sobrevida - Controle de Aplicações");

        setBounds(110, 160, 779, 391);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void avisoSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avisoSenhaMouseClicked
    }//GEN-LAST:event_avisoSenhaMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void imprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirMouseClicked
    }//GEN-LAST:event_imprimirMouseClicked

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        new Thread(){
            int i=0;
            public void run(){
                while(i<100){
                    i = i+5;
                    try{
                        imprimirCarregar.setVisible(true);
                        sleep(120);
                    }catch (Exception e){  
                    }
                }
                RelatorioController relatorioController = new RelatorioController();
                String dePegar = de.getText();
                String paraPegar = para.getText();
                if((!"  /  /    ".equals(dePegar)) && (!"  /  /    ".equals(paraPegar))){
                    imprimirCarregar.setVisible(false);
                    Object[] opcao = {"Sim", "Não"};
                    int respostaUsuario = JOptionPane.showOptionDialog(null, "Gerando relatório de controle de próximas doses.\nDeseja continuar?",
                            "Controle de aplicações", JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]
                    );
                    
                    if (respostaUsuario == JOptionPane.YES_OPTION) {
                        try {
                            imprimirCarregar.setVisible(true);
                            relatorioController.gerarPDF(de, para, imprimirCarregar);
                        } catch (IOException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                            Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (ParseException ex) {
                            Logger.getLogger(GerarRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else{
                    imprimirCarregar.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Por favor, preencher todos os campos obrigatórios!"
                        ,"Gerar relatório", JOptionPane.ERROR_MESSAGE
                    );
                    avisoDe.setVisible(true);
                    avisoPara.setVisible(true);
                }
            }
        }.start();
    }//GEN-LAST:event_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoDe;
    private javax.swing.JLabel avisoPara;
    private javax.swing.JPanel avisoSenha;
    private javax.swing.JFormattedTextField de;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel imprimirCarregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JSeparator linhaSeparador1;
    private javax.swing.JFormattedTextField para;
    // End of variables declaration//GEN-END:variables
}
