package br.com.sobrevida.vacinaSARSCoV2.view;

import br.com.sobrevida.vacinaSARSCoV2.controller.CidadaoController;
import br.com.sobrevida.vacinaSARSCoV2.model.CidadaoModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WERIKE
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    CidadaoController cidadaoController = new CidadaoController();
    CidadaoModel cidadaoModel = new CidadaoModel();
            
    public TelaPrincipal() {
        initComponents();
        
        //SE ALTO AJUSTA AO TAMANHO DO MONITOR
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //ALTERANDO O ICONE PADRAO DO JAVA
        Utilitario utilitario = new Utilitario();
        utilitario.inserirIcone(this);
        
        cadastroCidadaoTela.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktop = new javax.swing.JDesktopPane();
        cadastroCidadaoTela = new javax.swing.JPanel();
        closew = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        consulta = new javax.swing.JTextField();
        cadastroEmail = new javax.swing.JTextField();
        cadastroEndereco = new javax.swing.JTextField();
        sobreNome = new javax.swing.JTextField();
        idCodigo = new javax.swing.JTextField();
        cadastroCpf = new javax.swing.JTextField();
        cadastroCelular = new javax.swing.JTextField();
        cadastroEnderecoNumero = new javax.swing.JTextField();
        cadastroNascimento = new javax.swing.JTextField();
        primeiroNome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPacientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        botaoCadastroCidadao = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastroCidadao = new javax.swing.JMenu();
        btnCidadaoCadastro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnTiposVacinas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        trocarPerfil = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vacinação SARS-COV-2");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 740));
        setPreferredSize(new java.awt.Dimension(1366, 740));

        jDesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktop.setMaximumSize(new java.awt.Dimension(1366, 768));
        jDesktop.setMinimumSize(new java.awt.Dimension(1280, 720));
        jDesktop.setPreferredSize(new java.awt.Dimension(1366, 768));

        cadastroCidadaoTela.setBackground(new java.awt.Color(255, 255, 255));
        cadastroCidadaoTela.setForeground(new java.awt.Color(255, 255, 255));
        cadastroCidadaoTela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroCidadaoTelaMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.setLayout(null);

        closew.setBackground(new java.awt.Color(153, 0, 0));
        closew.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        closew.setForeground(new java.awt.Color(153, 0, 0));
        closew.setText("  X");
        closew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closewMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(closew);
        closew.setBounds(962, 12, 38, 24);
        cadastroCidadaoTela.add(jSeparator2);
        jSeparator2.setBounds(60, 400, 842, 2);
        cadastroCidadaoTela.add(jSeparator1);
        jSeparator1.setBounds(60, 68, 842, 2);

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Lista de Pacientes");
        cadastroCidadaoTela.add(jLabel38);
        jLabel38.setBounds(60, 364, 180, 30);

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Cadastro de Pacientes");
        cadastroCidadaoTela.add(jLabel13);
        jLabel13.setBounds(60, 32, 230, 30);

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Código");
        cadastroCidadaoTela.add(jLabel19);
        jLabel19.setBounds(60, 90, 100, 16);

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("CPF");
        cadastroCidadaoTela.add(jLabel24);
        jLabel24.setBounds(662, 190, 30, 16);

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Celular");
        cadastroCidadaoTela.add(jLabel22);
        jLabel22.setBounds(390, 190, 50, 16);

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Nº");
        cadastroCidadaoTela.add(jLabel30);
        jLabel30.setBounds(740, 240, 20, 16);

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("E-Mail");
        cadastroCidadaoTela.add(jLabel32);
        jLabel32.setBounds(60, 290, 40, 16);

        jLabel28.setBackground(new java.awt.Color(51, 51, 51));
        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Endereço");
        cadastroCidadaoTela.add(jLabel28);
        jLabel28.setBounds(60, 240, 60, 16);

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Data de Nascimento");
        cadastroCidadaoTela.add(jLabel18);
        jLabel18.setBounds(60, 190, 130, 16);

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nome completo");
        cadastroCidadaoTela.add(jLabel14);
        jLabel14.setBounds(60, 140, 100, 16);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*");
        cadastroCidadaoTela.add(jLabel31);
        jLabel31.setBounds(760, 240, 10, 15);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        cadastroCidadaoTela.add(jLabel25);
        jLabel25.setBounds(692, 190, 10, 15);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");
        cadastroCidadaoTela.add(jLabel23);
        jLabel23.setBounds(440, 190, 10, 15);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("*");
        cadastroCidadaoTela.add(jLabel33);
        jLabel33.setBounds(100, 290, 10, 15);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");
        cadastroCidadaoTela.add(jLabel29);
        jLabel29.setBounds(122, 240, 10, 15);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        cadastroCidadaoTela.add(jLabel20);
        jLabel20.setBounds(190, 190, 10, 15);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        cadastroCidadaoTela.add(jLabel15);
        jLabel15.setBounds(160, 140, 10, 15);

        pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        pesquisa.setForeground(new java.awt.Color(51, 51, 51));
        pesquisa.setText("Pesquisar");
        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
        });
        cadastroCidadaoTela.add(pesquisa);
        pesquisa.setBounds(622, 407, 280, 28);

        consulta.setBackground(new java.awt.Color(255, 255, 255));
        consulta.setForeground(new java.awt.Color(51, 51, 51));
        consulta.setText("Consultar...");
        consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                consultaMouseEntered(evt);
            }
        });
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                consultaKeyPressed(evt);
            }
        });
        cadastroCidadaoTela.add(consulta);
        consulta.setBounds(622, 32, 280, 28);

        cadastroEmail.setBackground(new java.awt.Color(255, 255, 255));
        cadastroEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroEmailMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroEmail);
        cadastroEmail.setBounds(230, 284, 390, 28);

        cadastroEndereco.setBackground(new java.awt.Color(255, 255, 255));
        cadastroEndereco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroEnderecoMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroEndereco);
        cadastroEndereco.setBounds(230, 234, 480, 28);

        sobreNome.setBackground(new java.awt.Color(255, 255, 255));
        sobreNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sobreNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreNomeMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(sobreNome);
        sobreNome.setBounds(522, 134, 380, 28);

        idCodigo.setEditable(false);
        idCodigo.setBackground(new java.awt.Color(255, 255, 255));
        idCodigo.setEnabled(false);
        idCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idCodigoMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(idCodigo);
        idCodigo.setBounds(230, 86, 110, 28);

        cadastroCpf.setBackground(new java.awt.Color(255, 255, 255));
        cadastroCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroCpfMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroCpf);
        cadastroCpf.setBounds(722, 184, 180, 28);

        cadastroCelular.setBackground(new java.awt.Color(255, 255, 255));
        cadastroCelular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroCelularMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroCelular);
        cadastroCelular.setBounds(470, 184, 150, 28);

        cadastroEnderecoNumero.setBackground(new java.awt.Color(255, 255, 255));
        cadastroEnderecoNumero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroEnderecoNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroEnderecoNumeroMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroEnderecoNumero);
        cadastroEnderecoNumero.setBounds(782, 234, 120, 28);

        cadastroNascimento.setBackground(new java.awt.Color(255, 255, 255));
        cadastroNascimento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cadastroNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastroNascimentoMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(cadastroNascimento);
        cadastroNascimento.setBounds(230, 184, 120, 28);

        primeiroNome.setBackground(new java.awt.Color(255, 255, 255));
        primeiroNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        primeiroNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primeiroNomeMouseClicked(evt);
            }
        });
        cadastroCidadaoTela.add(primeiroNome);
        primeiroNome.setBounds(230, 134, 270, 28);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Sobrenome");
        cadastroCidadaoTela.add(jLabel17);
        jLabel17.setBounds(522, 163, 100, 15);

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("000.000.000-00");
        cadastroCidadaoTela.add(jLabel27);
        jLabel27.setBounds(722, 213, 120, 15);

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("00 9 0000-0000");
        cadastroCidadaoTela.add(jLabel26);
        jLabel26.setBounds(470, 213, 120, 15);

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Rua - Avenida - Ap. - Praça... ");
        cadastroCidadaoTela.add(jLabel34);
        jLabel34.setBounds(230, 263, 170, 15);

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Número do local");
        cadastroCidadaoTela.add(jLabel35);
        jLabel35.setBounds(782, 263, 100, 15);

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Endereço de E-mail");
        cadastroCidadaoTela.add(jLabel36);
        jLabel36.setBounds(230, 313, 120, 15);

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("dd/mm/aaaa");
        cadastroCidadaoTela.add(jLabel21);
        jLabel21.setBounds(230, 213, 120, 15);

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Código do usuário");
        cadastroCidadaoTela.add(jLabel37);
        jLabel37.setBounds(231, 115, 110, 15);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Primeiro nome");
        cadastroCidadaoTela.add(jLabel16);
        jLabel16.setBounds(230, 163, 100, 15);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salvarKeyPressed(evt);
            }
        });
        cadastroCidadaoTela.add(salvar);
        salvar.setBounds(590, 334, 140, 30);

        deletar.setText("Deletar");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });
        cadastroCidadaoTela.add(deletar);
        deletar.setBounds(762, 640, 140, 30);

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        cadastroCidadaoTela.add(alterar);
        alterar.setBounds(590, 640, 140, 30);

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        limpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                limparKeyPressed(evt);
            }
        });
        cadastroCidadaoTela.add(limpar);
        limpar.setBounds(762, 334, 140, 30);

        listaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Nascimento", "Celular", "CPF", "Endereço", "Nº", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPacientes);
        if (listaPacientes.getColumnModel().getColumnCount() > 0) {
            listaPacientes.getColumnModel().getColumn(0).setResizable(false);
        }

        cadastroCidadaoTela.add(jScrollPane1);
        jScrollPane1.setBounds(60, 440, 842, 190);

        jDesktop.add(cadastroCidadaoTela);
        cadastroCidadaoTela.setBounds(0, 0, 1004, 730);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jButton13.setText("Carteira de vacina");
        jPanel1.add(jButton13);
        jButton13.setBounds(50, 420, 260, 70);

        jButton11.setText("Cadastrar Doses");
        jPanel1.add(jButton11);
        jButton11.setBounds(50, 300, 260, 70);

        jButton12.setText("Cadastrar Vacina");
        jPanel1.add(jButton12);
        jButton12.setBounds(50, 180, 260, 70);

        botaoCadastroCidadao.setText("Cadastrar Cidadão");
        botaoCadastroCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroCidadaoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastroCidadao);
        botaoCadastroCidadao.setBounds(50, 60, 260, 70);

        usuario.setText("Seja bem vindo, werike!");
        usuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(usuario);
        usuario.setBounds(210, 10, 200, 16);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 47, 61));
        jLabel2.setText("Powered by Group Seven LTDA ® ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 660, 210, 15);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\Projeto_Vacina_Codiv19\\PROJETO\\vacinaSARS-CoV-2\\src\\main\\java\\br\\com\\sobrevida\\vacinaSARSCoV2\\view\\image\\transparente.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, -10, 370, 810);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\Projeto_Vacina_Codiv19\\PROJETO\\vacinaSARS-CoV-2\\src\\main\\java\\br\\com\\sobrevida\\vacinaSARSCoV2\\view\\image\\painel1.jpg")); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(-1250, -20, 1660, 870);

        jDesktop.add(jPanel1);
        jPanel1.setBounds(1000, 0, 370, 780);

        jLabel9.setText("Setor de segurança publica");
        jDesktop.add(jLabel9);
        jLabel9.setBounds(680, 280, 150, 40);

        jLabel8.setText("Setor de educação");
        jDesktop.add(jLabel8);
        jLabel8.setBounds(370, 280, 110, 40);

        jLabel7.setText("Gestantes cadastrados");
        jDesktop.add(jLabel7);
        jLabel7.setBounds(60, 280, 130, 40);

        jLabel6.setText("Crianças cadastrados");
        jDesktop.add(jLabel6);
        jLabel6.setBounds(680, 70, 110, 40);

        jLabel5.setText("Adultos cadastrados");
        jDesktop.add(jLabel5);
        jLabel5.setBounds(370, 70, 110, 40);

        jLabel3.setText("Idosos cadastrados");
        jDesktop.add(jLabel3);
        jLabel3.setBounds(80, 70, 110, 40);

        jLabel4.setText("20");
        jDesktop.add(jLabel4);
        jLabel4.setBounds(260, 150, 20, 30);
        jDesktop.add(jButton1);
        jButton1.setBounds(56, 65, 260, 150);
        jDesktop.add(jButton9);
        jButton9.setBounds(676, 485, 260, 150);
        jDesktop.add(jButton8);
        jButton8.setBounds(366, 485, 260, 150);
        jDesktop.add(jButton7);
        jButton7.setBounds(56, 485, 260, 150);
        jDesktop.add(jButton6);
        jButton6.setBounds(676, 275, 260, 150);
        jDesktop.add(jButton5);
        jButton5.setBounds(366, 275, 260, 150);
        jDesktop.add(jButton3);
        jButton3.setBounds(56, 275, 260, 150);
        jDesktop.add(jButton4);
        jButton4.setBounds(676, 65, 260, 150);
        jDesktop.add(jButton2);
        jButton2.setBounds(366, 65, 260, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\Projeto_Vacina_Codiv19\\PROJETO\\vacinaSARS-CoV-2\\src\\main\\java\\br\\com\\sobrevida\\vacinaSARSCoV2\\View\\Image\\painel1.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jDesktop.add(jLabel1);
        jLabel1.setBounds(-250, -20, 1920, 870);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1280, 720));

        menuCadastroCidadao.setText("Cadastro");

        btnCidadaoCadastro.setText("Cidadão");
        btnCidadaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCidadaoCadastroActionPerformed(evt);
            }
        });
        menuCadastroCidadao.add(btnCidadaoCadastro);

        jMenuItem1.setText("Vacinação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastroCidadao.add(jMenuItem1);

        jMenuBar1.add(menuCadastroCidadao);

        jMenu2.setText("Vacinas");

        btnTiposVacinas.setText("Tipos de vacinas");
        btnTiposVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiposVacinasActionPerformed(evt);
            }
        });
        jMenu2.add(btnTiposVacinas);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sistema");
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Sair");

        trocarPerfil.setText("Trocar perfil");
        trocarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trocarPerfilMouseClicked(evt);
            }
        });
        trocarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocarPerfilActionPerformed(evt);
            }
        });
        jMenu3.add(trocarPerfil);

        sair.setText("Exit");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu3.add(sair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCidadaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCidadaoCadastroActionPerformed
        cadastroCidadaoTela.setVisible(true);
    }//GEN-LAST:event_btnCidadaoCadastroActionPerformed

    private void btnTiposVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiposVacinasActionPerformed
        //TipoVacinaCadastro tipoVacinaCadastro = new TipoVacinaCadastro();
        //jDesktop.add(tipoVacinaCadastro);
        //tipoVacinaCadastro.setVisible(true);
    }//GEN-LAST:event_btnTiposVacinasActionPerformed
    private void trocarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trocarPerfilMouseClicked
    }//GEN-LAST:event_trocarPerfilMouseClicked
    private void trocarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarPerfilActionPerformed
        JOptionPane.showMessageDialog(null, "O programa será reiniciado!" 
            ,"Atenção", JOptionPane.WARNING_MESSAGE);
        
        TelaPrincipal.this.dispose();
        new TelaPrincipal().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Carregar carregar = new Carregar();
        carregar.setVisible(true);
    }//GEN-LAST:event_trocarPerfilActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        JOptionPane.showMessageDialog(null, "O programa será Finalizado!" 
            ,"Atenção", JOptionPane.WARNING_MESSAGE);
        
        TelaPrincipal.this.dispose();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_sairActionPerformed
    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
    }//GEN-LAST:event_sairMouseClicked
    private void botaoCadastroCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroCidadaoActionPerformed
        cadastroCidadaoTela.setVisible(true);
    }//GEN-LAST:event_botaoCadastroCidadaoActionPerformed

    private void closewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closewMouseClicked
        cadastroCidadaoTela.setVisible(false);
    }//GEN-LAST:event_closewMouseClicked

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        
        String primeiro = (primeiroNome.getText());
        String segundo = (sobreNome.getText());
        String nome = primeiro+" "+segundo;
        
        String nascimento = (cadastroNascimento.getText());
        String celular = (cadastroCelular.getText());
        String cpf = (cadastroCpf.getText());
        String endereco = (cadastroEndereco.getText());
        String numero = (cadastroEnderecoNumero.getText());
        String email = (cadastroEmail.getText());
        
        boolean cadastro = cidadaoController.salvar(nome, nascimento, celular,
            cpf, endereco, numero, email, false);
        
        if(cadastro == true){
            
            JOptionPane.showMessageDialog(null, "Usuário cancelado com sucesso!"
                ,"Deletar Usuário", JOptionPane.WARNING_MESSAGE);
                
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!\n"
                + "Por favor, verifique e tente novamente."
                ,"Cadastro de Paciênte", JOptionPane.WARNING_MESSAGE
            );
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salvarKeyPressed
        
        String primeiro = (primeiroNome.getText());
        String segundo = (sobreNome.getText());
        String nome = primeiro+" "+segundo;
        
        String nascimento = (cadastroNascimento.getText());
        String celular = (cadastroCelular.getText());
        String cpf = (cadastroCpf.getText());
        String endereco = (cadastroEndereco.getText());
        String numero = (cadastroEnderecoNumero.getText());
        String email = (cadastroEmail.getText());
        
        boolean cadastro = cidadaoController.salvar(nome, nascimento, celular,
            cpf, endereco, numero, email, false);
        
        if(cadastro == true){
            
            JOptionPane.showMessageDialog(null, "Cidadão cadastrado com sucesso!"
                ,"Cadastro de Usuário", JOptionPane.WARNING_MESSAGE);
                
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!\n"
                + "Por favor, verifique e tente novamente."
                ,"Cadastro de Paciênte", JOptionPane.WARNING_MESSAGE
            );
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }
    }//GEN-LAST:event_salvarKeyPressed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        idCodigo.setText("");
        primeiroNome.setText("");
        sobreNome.setText("");
        cadastroNascimento.setText("");
        cadastroCelular.setText("");
        cadastroCpf.setText("");
        cadastroEndereco.setText("");
        cadastroEnderecoNumero.setText("");
        cadastroEmail.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void limparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_limparKeyPressed
       idCodigo.setText("");
       primeiroNome.setText("");
       sobreNome.setText("");
       cadastroNascimento.setText("");
       cadastroCelular.setText("");
       cadastroCpf.setText("");
       cadastroEndereco.setText("");
       cadastroEnderecoNumero.setText("");
       cadastroEmail.setText("");
    }//GEN-LAST:event_limparKeyPressed
    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
    }//GEN-LAST:event_consultaActionPerformed
    private void consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaMouseClicked
        consulta.setText("");
    }//GEN-LAST:event_consultaMouseClicked
    private void idCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idCodigoMouseClicked
    }//GEN-LAST:event_idCodigoMouseClicked
    private void primeiroNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeiroNomeMouseClicked
    }//GEN-LAST:event_primeiroNomeMouseClicked
    private void sobreNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreNomeMouseClicked
    }//GEN-LAST:event_sobreNomeMouseClicked
    private void cadastroNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroNascimentoMouseClicked
    }//GEN-LAST:event_cadastroNascimentoMouseClicked
    private void cadastroCidadaoTelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroCidadaoTelaMouseClicked
        consulta.setText("Consultar...");
    }//GEN-LAST:event_cadastroCidadaoTelaMouseClicked
    private void cadastroCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroCelularMouseClicked
    }//GEN-LAST:event_cadastroCelularMouseClicked
    private void cadastroCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroCpfMouseClicked
    }//GEN-LAST:event_cadastroCpfMouseClicked
    private void cadastroEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroEnderecoMouseClicked
    }//GEN-LAST:event_cadastroEnderecoMouseClicked
    private void cadastroEnderecoNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroEnderecoNumeroMouseClicked
    }//GEN-LAST:event_cadastroEnderecoNumeroMouseClicked
    private void cadastroEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastroEmailMouseClicked
    }//GEN-LAST:event_cadastroEmailMouseClicked
    private void consultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaMouseEntered
    }//GEN-LAST:event_consultaMouseEntered
    private void consultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaKeyPressed
        String pesquisaID = (consulta.getText());
        int consultaID = Integer.parseInt(pesquisaID);

        CidadaoModel resultCidadaoModel = cidadaoController.consultar(consultaID);

        int id = resultCidadaoModel.getId();
        String resultID = Integer.toString(id);
        
        String nome = resultCidadaoModel.getNome();
        String[] resultado = nome.split(" ");
        String primeiro = resultado[0];
        String segundo = resultado[1];
        
        String nascimento = resultCidadaoModel.getNascimento();
        String celular = resultCidadaoModel.getCelular();
        String cpf = resultCidadaoModel.getCpf();
        String endereco = resultCidadaoModel.getEndereco();
        String numero = resultCidadaoModel.getN();
        String email = resultCidadaoModel.getEmail();
        
        idCodigo.setText(resultID);
        primeiroNome.setText(primeiro);
        sobreNome.setText(segundo);
        cadastroNascimento.setText(nascimento);
        cadastroCelular.setText(celular);
        cadastroCpf.setText(cpf);
        cadastroEndereco.setText(endereco);
        cadastroEnderecoNumero.setText(numero);
        cadastroEmail.setText(email);
    }//GEN-LAST:event_consultaKeyPressed
    private void pesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyPressed
    }//GEN-LAST:event_pesquisaKeyPressed
    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        String dado = pesquisa.getText();
        cidadaoController.pesquisa(listaPacientes, dado);
    }//GEN-LAST:event_pesquisaKeyReleased
    private void listaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPacientesMouseClicked
    }//GEN-LAST:event_listaPacientesMouseClicked
    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        int linhaSelecionada = listaPacientes.getSelectedRow();
        
        int id = (int) listaPacientes.getModel().getValueAt(linhaSelecionada, 0);
        String nome = listaPacientes.getModel().getValueAt(linhaSelecionada, 1).toString();        
        String nascimento = listaPacientes.getModel().getValueAt(linhaSelecionada, 2).toString();
        String celular = listaPacientes.getModel().getValueAt(linhaSelecionada, 3).toString();
        String cpf = listaPacientes.getModel().getValueAt(linhaSelecionada, 4).toString();
        String endereco = listaPacientes.getModel().getValueAt(linhaSelecionada, 5).toString();
        String numero = listaPacientes.getModel().getValueAt(linhaSelecionada, 6).toString();
        String email = listaPacientes.getModel().getValueAt(linhaSelecionada, 7).toString();
        
        boolean cadastro = cidadaoController.alterar(id, nome, nascimento, celular,
            cpf, endereco, numero, email, false);
        
        if(cadastro == true){
            
            JOptionPane.showMessageDialog(null, "Cidadão cadastrado com sucesso!"
                ,"Cadastro de Usuário", JOptionPane.WARNING_MESSAGE);
                
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!\n"
                + "Por favor, verifique e tente novamente."
                ,"Cadastro de Paciênte", JOptionPane.WARNING_MESSAGE
            );
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
    int linhaSelecionada = listaPacientes.getSelectedRow();
    String nome = listaPacientes.getModel().getValueAt(linhaSelecionada, 1).toString();
        
        int id = (int) listaPacientes.getModel().getValueAt(linhaSelecionada, 0);
        
        boolean cadastro = cidadaoController.deletar(id, nome, false);
        
        if(cadastro == true){
            
            JOptionPane.showMessageDialog(null, "Cidadão cadastrado com sucesso!"
                ,"Cadastro de Usuário", JOptionPane.WARNING_MESSAGE);
                
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!\n"
                + "Por favor, verifique e tente novamente."
                ,"Cadastro de Paciênte", JOptionPane.WARNING_MESSAGE
            );
            primeiroNome.setText("");
            sobreNome.setText("");
            cadastroNascimento.setText("");
            cadastroCelular.setText("");
            cadastroCpf.setText("");
            cadastroEndereco.setText("");
            cadastroEnderecoNumero.setText("");
            cadastroEmail.setText("");
        }
    }//GEN-LAST:event_deletarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton botaoCadastroCidadao;
    private javax.swing.JMenuItem btnCidadaoCadastro;
    private javax.swing.JMenuItem btnTiposVacinas;
    private javax.swing.JTextField cadastroCelular;
    private javax.swing.JPanel cadastroCidadaoTela;
    private javax.swing.JTextField cadastroCpf;
    private javax.swing.JTextField cadastroEmail;
    private javax.swing.JTextField cadastroEndereco;
    private javax.swing.JTextField cadastroEnderecoNumero;
    private javax.swing.JTextField cadastroNascimento;
    private javax.swing.JLabel closew;
    private javax.swing.JTextField consulta;
    private javax.swing.JButton deletar;
    private javax.swing.JTextField idCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton limpar;
    private javax.swing.JTable listaPacientes;
    private javax.swing.JMenu menuCadastroCidadao;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JTextField primeiroNome;
    private javax.swing.JMenuItem sair;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField sobreNome;
    private javax.swing.JMenuItem trocarPerfil;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}