# 1 - CRIANDO TABELA CADASTRO DE USUÁRIO
CREATE TABLE usuario(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    idPerfil INT NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(16) NOT NULL,
    FOREIGN KEY (idPerfil) REFERENCES perfil(id)
);

# 2 - INSERINDO USUARIO
INSERT INTO bd_vacina_sars_cov_2.usuario (idPerfil, email, senha) VALUES ('3', 'werike', '1');

# 3 - OBS: PARA INSERIR MAIS USUÁRIO BASTA COPIAR A LINHA ACIMA E ALTERAR SOMENTE OS 'VALUES'.


# 4 - VERIFICANDO SE FOI CADASTRADO
SELECT * FROM usuario;