#CRIANDO TABELA CIDADAO
CREATE TABLE cidadao(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(60),
	nascimento VARCHAR(10),
	celular VARCHAR(14),
	cpf VARCHAR(14) UNIQUE,
	endereco VARCHAR(100),
    numero VARCHAR(20),
	email VARCHAR(80)
);